apiVersion: v1
kind: Secret
metadata:
  name: gotagnews-secret-line-secret
type: Opaque
data:
  line-secret: ENC[AES256_GCM,data:q1zusCJImWSg/LjxfF6IlWK++v8timKVS0owR6PiogrPqw0CmkYjtyp0Uk8=,iv:IG43JqRpDvTAetMLmhu7Hir7oAoIh9upssoU5hNkjcY=,tag:iPoW45CoJD75evWWXjnryQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1a3f9l459k30wqnyg4rerhpg432xq23r085n2uk278svp2t3zjv3qdxch3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0amhteGNTS1U0WGNoWkVP
        TXlWbEFqYko4RjVjdENNU0tLSzA2Qmpncng0ClJiTTlmcXBZdG1oY25mbDRsUS9p
        c2Rrbm5DYlY4bWRHaXI3Q0tneHFzaGsKLS0tIGo0S2E4cWF1c2djU3IrOC9ad0ov
        RUljWTVobUpzYXRaRVhSUDRna0s0TVEKH741QKn2bd1HvzDFHQk/NaL/2uZ+oE17
        AR5NDjng74ueVoLRuIvqzjdOrB/fKLy0Xgzg/j/qTlbOxQ4SEVFwaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-30T14:15:38Z"
  mac: ENC[AES256_GCM,data:PQ1wXs2SxKq58MozGbFabn8bitiEkzFyhQlun9tBahxbgi0ru8XySygAqQzTHXliUwGsfUv7btXn/d1+1mHZMfTrCsH5R3HF0uVmOZfo2/saZYxXEIuFGqd6WCYOcwnSziYyZNw0bqqYVnVVYbWtgqt/DoTgvnzuigIYtQCoujs=,iv:OdshxAZYSmTWkBAnHfJJZE0EGyob/SqwUOwCNnzr8xc=,tag:jpByxw9fRf/sFJrF8B2zWg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
