apiVersion: batch/v1
kind: CronJob
metadata:
  name: gotagnews
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gotagnews
              image: takokun778/gotagnews:latest
              imagePullPolicy: Always
              env:
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: gotagnews-secret-mongodb-uri
                      key: mongodb-uri
                - name: LINE_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: gotagnews-secret-line-secret
                      key: line-secret
                - name: LINE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: gotagnews-secret-line-token
                      key: line-token
          restartPolicy: Never
