services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - ../:/app
    restart: always
