name: go container
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  container-push:
    runs-on: ubuntu-22.04
    outputs:
      image-tag: ${{ steps.build-and-push.outputs.image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create tag
        id: create-tag
        run: |
          TAG=`date +%Y-%m-%d-%H-%M-%S`
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.7
      - name: Install ko
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua install -t ko
      - name: Docker login
        run: ko login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} index.docker.io
      - name: Container build and push
        id: build-and-push
        working-directory: ./cmd/app
        run: |
          KO_DOCKER_REPO=${{ secrets.DOCKERHUB_USERNAME }}/gotagnews \
          SOURCE_DATE_EPOCH=$(date +%s) \
          ko build --sbom=none --bare --tags=${{ env.TAG }},latest ./ --platform=linux/amd64
