name: go container
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  container-push:
    runs-on: ubuntu-22.04
    outputs:
      image-name: ${{ steps.build-and-push.outputs.image-name }}
      image-tag: ${{ steps.build-and-push.outputs.image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Set up ko
        run: go install github.com/google/ko@latest
      - name: Docker login
        run: ko login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} index.docker.io
      - name: Container build and push
        id: build-and-push
        working-directory: ./cmd/app
        run: |
          IMAGE_NAME=gotagnews
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

          IMAGE_TAG="test"
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

          KO_DOCKER_REPO=${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME} \
          SOURCE_DATE_EPOCH=$(date +%s) \
          ko build --sbom=none --bare --tags=${IMAGE_TAG},latest ./ --platform=linux/amd64
