name: okteto deploy
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/okteto.deploy.yaml
      - k8s/*.yaml
  schedule:
    - cron: '0 15 * * *'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install okteto
        run: curl https://get.okteto.com -sSfL | sh
      - name: Okteto login
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      - name: Okteto deploy
        run: okteto deploy --namespace takokun778
